### ISSUE TITLE
Dataset - Larval Dungeness crab arrival timing, abundance, and size along the coast of British Columbia

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#109]
## Larval Dungeness crab arrival timing, abundance, and size along the coast of British Columbia

<https://hakaiinstitute.github.io/hakai-metadata-entry-form/#/en/hakai/57FPdLIBPcb9BOLfIOW44RJVywN2/-N1KAki3SSBEw0aHCoSv>

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [x] Time series datasets should include “time series” at the end of the title

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [x] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [x] A DOI has been drafted for this record
- [x] DOI has been updated via the form after review and changes to record
- [x] DOI has been manually edited on datacite fabrica
- [x] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [x] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] If resource is (partially) generated by Hakai researchers, include 'Tula Foundation' (with associated ROR) with 'Funder' role. Be sure to uncheck 'include in citation' for Tula Foundation.

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [x] Readme, changelog, data dictionary, protocols included in data-package (for tabular text based data)
- [ ] An archive folder, or other means, for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [x] All files in the data package can be opened and are not corrupt
- [x] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by timvdstap** [comment]
Hey @heather-earle I just wanted to let you know I'll have a look at this record submission this week and will let you know if I have any comments or suggestions!

**Comment by timvdstap** [comment]
Hey @heather-earle also a few comments and suggestions to this record, many will overlap with the sea surface temperature record:

- [ ] I noticed that the DOI is already Findable, but currently wouldn't resolve to anything (record is not published). I would recommended publishing this metadata record soon, even if it's 'only' as a metadata-only record.
- [ ] Given that the research is 'Ongoing', I have removed the 'end data when data was last collected' (2023-09-01).
- [ ] Version is 1.1, which to me implies that there's been a version 1.0 published somewhere. Is this the case (I don't think so?) If not, I would recommend changing to 1.0
- [ ] License is currently CC-BY-4-NC, but in the DMP it is mentioned that the data will be shared under CC-BY-4; is there a specific for CC-BY-4-NC?
- [x] In the Taxonomic Classification, I have included Metacarcinus magister 
- [ ] As this is a biological dataset, the _Geographic Extent_ field is required. I've included `Coastal British Columbia`, please verify :) 
- [x] I've added the ORCID and ROR for Lauren, and the ORCID for Matt Whalen.
- [x] I've included Tula Foundation as a Funder, please verify.  
- [ ] Lots of communities and First Nations added as project contributors -- should these also be included in the temperature data record?
- [ ] I would recommend removing the websites from the Primary Resource section - they are not the resources being described by this metadata. I would perhaps suggest adding those links under 'Resources' in the Readme file of the GitHub repository. I don't see a good relationship for adding them as 'Related Works', unless these websites reference the data records?
- [ ] I would recommend adding 'Light Trap Sampling Instructions' to the Lineage section (see how I've done). 
- [ ] The primary resource should link to the GitHub repository that includes the dataset (https://github.com/HakaiInstitute/sentinels-light-trap-public). adding the webistes for the Sentinels of Change and PNCRG to the 'Related Works' section, with relation type `
- [ ] As Related Works, consider adding a link to the Data Management Plan, as well as to the record with sea surface temperatures in BC. Once data is subsetted to Darwin Core and published to OBIS we can add that link as Related Work as well.
- [ ] Once you've added the GitHub repository as primary resource let me know, I can review the contents there as well 👍

**Comment by timvdstap** [comment]
Hi @heather-earle following your update about having reviewed the metadata record I was able to tick off most items on the list (see above) however there are still a few outstanding, mainly around the version number and license. Could you briefly check the outstanding items from the list above?

**Comment by heather-earle** [comment]
Hi Tim, okay great I've made the following changes:
-updated title, now less than 60 characters
-version is 1.0 now
-I have deleted the websites from resources, I think Lauren will add them to the readme file
-I have added the public repo as the primary resource, but not sure I named or described it in the best way? Open to feedback/edits!

Questions from me:
-do you need me to do anything for the DOI?
-I cannot actually select CC-BY-4 in the. metadata entry tool, it's not coming up as an option. Any ideas?
-Since the temp loggers are autonomously recording and there is no active data collection required from our partners to obtain this data, is it necessary to include them as contributors? We certainly can, I just wasn't sure if it was needed

**Comment by timvdstap** [comment]
> Hi Tim, okay great I've made the following changes: -updated title, now less than 60 characters -version is 1.0 now -I have deleted the websites from resources, I think Lauren will add them to the readme file -I have added the public repo as the primary resource, but not sure I named or described it in the best way? Open to feedback/edits!

This is great - thank you Heather! I'm not seeing the changes, just want to confirm that you've saved your edits?

> Questions from me: -do you need me to do anything for the DOI? -I cannot actually select CC-BY-4 in the. metadata entry tool, it's not coming up as an option. Any ideas? -Since the temp loggers are autonomously recording and there is no active data collection required from our partners to obtain this data, is it necessary to include them as contributors? We certainly can, I just wasn't sure if it was needed

I don't need anything from you for the DOI - once we're happy with the metadata I can select 'update DOI' which will automatically update the information in DataCite (which generates the DOI). I will go to DataCite to manually verify that the information is all accurate. I'm not sure why you can't select CC-BY-4.... this dropdown screen doesn't appear for you?

![image](https://github.com/user-attachments/assets/c686a050-0ca9-40f0-91b8-4d5d70da78d1)

As for temp data collection - if there's no active collection happening from their part then I'm not sure if it would make sense to add them as contributors, I'll leave that call up to you though! We can definitely leave it as is :)

**Comment by heather-earle** [comment]
Yes that dropdown does appear and I had selected that one - CC attribution 4.0 Attribution. But it seems that was the one coming up as CC-BY-4-NC?

**Comment by timvdstap** [comment]
> Yes that dropdown does appear and I had selected that one - CC attribution 4.0 Attribution. But it seems that was the one coming up as CC-BY-4-NC?

Not sure... but CC-BY-4 is selected now at least :)

**Comment by timvdstap** [comment]
Metadata record published to the Hakai Catalogue - should show up there within 24 hrs :)
