### ISSUE TITLE
Dataset - Fraser River Landslide Project - Sites of Concern 2024

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#115]
## Fraser River Landslide Project - Sites of Concern 2024

<https://hakaiinstitute.github.io/hakai-metadata-entry-form/#/en/hakai/RvRPlFMSsIaBwoGdQIq5BVYfBBa2/-NTLT7n49Ox3SnVoy6nW>

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [x] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [x] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [x] A DOI has been drafted for this record
- [x] DOI has been updated via the form after review and changes to record
- [ ] DOI has been manually edited on datacite fabrica
- [ ] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [ ] ROR and ORCID(s) are included and linked properly where applicable
- [ ] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] If resource is (partially) generated by Hakai researchers, include 'Tula Foundation' (with associated ROR) with 'Funder' role. Be sure to uncheck 'include in citation' for Tula Foundation.

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package (for tabular text based data)
- [ ] An archive folder, or other means, for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [x] All files in the data package can be opened and are not corrupt
- [x] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by timvdstap** [comment]
Thanks @hakaiholmes, some minor suggestions / comments:

- [ ] Not really sure what the questions are in the abstract? Seems like the abstract is copied over from some report and there's references to other sections throughout, which don't really make sense to have included in this abstract.
- [ ] There's an end date provided for the last data collection, but dataset status is 'ongoing'. Should status be changed?
- [ ] Not sure if the date revised makes sense to me - currently it shows that data was published in 2024, but the revision date is 2023? As such, the current recommended citation shows (2023) as date. Think this should be 2024 based on the report?
- [ ] Under the 'Hakai Institute' contact, Jenn Burt's email / position are provided but not her name? Does she need to be included in the recommended citation?
- [ ] I would again argue that the names listed in the report should be listed as authors / included in the recommended citation for this report?
- [ ] Wondering if it's better to replace the Related Works listed with the DOIs, e.g. for the 2021 Fraser River Landslides use: https://doi.org/10.21966/ytgc-6g46, and for the 2022 Fraser River Landslides: https://doi.org/10.21966/zjc2-b004?

Love how descriptive you've been with the platforms/instruments! 
- [ ] For the 'Phaseone Industrial instrument, you'll have to indicate which platform the instrument is attached to.

**Comment by timvdstap** [comment]
Awesome Keith, thanks - it looks great! The only thing I did was remove Jenn Burt's contact details from the 'Hakai Institute' contact and added some spacing in the abstract. If you're all OK with that then I can go ahead and publish the record - I will haggle Derek about creating an ORCID another time but let's not have that be a bottleneck for publication ;)

**Comment by hakaiholmes** [comment]
Thanks - lets publish it!

**Comment by timvdstap** [comment]
Done!
