### ISSUE TITLE
Dataset - Denali Fault - 2024 - Airborne LiDAR Survey

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#117]
## Denali Fault - 2024 - Airborne LiDAR Survey

<https://hakaiinstitute.github.io/hakai-metadata-entry-form/#/en/hakai/RvRPlFMSsIaBwoGdQIq5BVYfBBa2/-OCKOQlOxJdTg_BFOoXb>

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [ ] Frontloaded (with the most important information first)
- [ ] Include the geographical region the data apply to
- [x] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [x] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [x] A DOI has been drafted for this record
- [x] DOI has been updated via the form after review and changes to record
- [ ] DOI has been manually edited on datacite fabrica
- [ ] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [ ] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] If resource is (partially) generated by Hakai researchers, include 'Tula Foundation' (with associated ROR) with 'Funder' role. Be sure to uncheck 'include in citation' for Tula Foundation.

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package (for tabular text based data)
- [ ] An archive folder, or other means, for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [ ] All files in the data package can be opened and are not corrupt
- [ ] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by hakaiholmes** [comment]
Agree
Agree
Agree
I just updated it to research aeroplane and saved it as the default for future records. Thanks!

**Comment by hakaiholmes** [comment]
Kisik was added as a contact and in the citation - just checking with Derek on that update now.

**Comment by timvdstap** [comment]
> Kisik was added as a contact and in the citation - just checking with Derek on that update now.

Sounds good, just make sure to give them a role ;-)

**Comment by hakaiholmes** [comment]
yes, I saw that and updated it. At lease I am pretty sure... yes - we are good on Denali.

**Comment by timvdstap** [comment]
Looks great to me, will publish to the catalogue!
