### ISSUE TITLE
Dataset - Biodiversity Surveys of the Gwaxdlala/Nalaxdlala IPCA in Knight Inlet, British Columbia

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#55]
## Biodiversity Surveys of the Gwaxdlala/Nalaxdlala IPCA in Knight Inlet, British Columbia

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/4TvAwNKXC7PkAi0TEZsZbbAzXfi1/-NOHQei0clSbCzMMFHdq

### In General
- [ ] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [ ] No version information in the title
- [ ] Frontloaded (with the most important information first) 
- [ ] Include the geographical region the data apply to 
- [ ] Short – aim for 60 characters including spaces 
- [ ] Does not include acronyms – put these in the keywords 
- [ ] Does not include the word “dataset” 
- [ ] Time series datasets should include “time series” at the end of the title 
- [ ] Does not include the time period (this is covered in the temporal extents fields)

#### Abstract

- [ ] Abbreviations have been expanded upon at first mention

### Spatial

- [ ] Ensure that Depth or Height Positive is correctly selected

### Contact

- [ ] No organizations listed under first / last name
- [ ] ROR and ORCID(s) are included and linked properly where applicable
- [ ] The citation in the metadata record matches the preferred citation mentioned in the data package. 
- [ ] Include Hakai Institute as Publisher (& Distributor?)

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package
- [ ] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [ ] Links work
- [ ] Resource link links to a download of the compressed data package (.zip) of the correct version.
- [ ] All files in the data package can be opened and are not corrupt

**Comment by hakaiholmes** [comment]
Title: acronym used ~ IPCA ~ consider leaving this out of the title or write it all out if important.
The abstract is brief but does answer all my questions. 
No limitations affecting the dataset?
Contact: ~ Include Hakai Institute as Publisher (& Distributor?)
Contact: No Orcids or ROR needed? Not sure if you need this for an ongoing dataset, but figured I would check.
Resources ~ the google drive link doesn't seem to take me to the specific folder ~ is it public / check the sharing settings. I am unable to get to the csv file to check out the species list. Please ensure outsiders are able to access this link.
Resources: The edna link works - please add a description for the link. Are you able to access the data from this page? I just see a general information sheet ~ maybe you need to login for further access in which case disregard this comment.

That is it for me - ping me with the edna resource link so I can have a look at that.
Thanks and fantastic work!

**Comment by timvdstap** [comment]
@timvdstap tagging myself to mint a draft DOI for this record once comments are addressed

**Comment by carolynisabella** [comment]
> Title: acronym used ~ IPCA ~ consider leaving this out of the title or write it all out if important. 

**Good point, we have updated the title with Indigenous Protected and Conserved Area (IPCA) fully spelled out**

The abstract is brief but does answer all my questions. 

**Also good point. We have expanded the Abstract to include more information and also have more details in the README file housed in the Google Drive folder**

No limitations affecting the dataset? 

Contact: ~ Include Hakai Institute as Publisher (& Distributor?) 

**Thank you, we made this change to the Contacts List (just added Hakai Institute as Publisher)**

Contact: No Orcids or ROR needed? Not sure if you need this for an ongoing dataset, but figured I would check. 
 
**Thanks for checking - I'm sure most folks do have ORCIDs, just need to track them down. Can always update later if we don't get them in time for initial publication of this dataset**

Resources ~ the google drive link doesn't seem to take me to the specific folder ~ is it public / check the sharing settings. I am unable to get to the csv file to check out the species list. Please ensure outsiders are able to access this link. 

**We will look into this and make sure it is accessible now - should check again before publishing**

Resources: The edna link works - please add a description for the link. Are you able to access the data from this page? I just see a general information sheet ~ maybe you need to login for further access in which case disregard this comment.

**Once on the NCBI page, the data associated with each sample is available under 'Project Data' --> BioSample **

> 
> That is it for me - ping me with the edna resource link so I can have a look at that. Thanks and fantastic work!

**Thanks for your review, Keith!**

**Comment by carolynisabella** [comment]
Tim et al. - can you advise on how to make the Google Drive folder publicly accessible? The only options I see are 'Restricted' or within Hakai Institute anyone with the link can access. Is there another sharing setting somewhere we should be updating?

**Comment by zmonteith** [comment]
Hi @carolynisabella, I can't seem to see a google drive link in the resource section, did it get removed temporarily? If you send me the link, I'm happy to see if I can change the access settings

**Comment by carolynisabella** [comment]
Thanks @zmonteith ! sorry about that, link should be there now. Copying it here too.
https://drive.google.com/drive/folders/199hpW6jZnNRxK7KB7MTLs_t3cIFD65wo?usp=share_link

**Comment by carolynisabella** [comment]
Thanks, Zach! Also just a note (for all) just I just updated the Abstract with a little more detail.

**Comment by hakaiholmes** [comment]
Everything on my list checks out. Fantastic job.

**Comment by timvdstap** [comment]
Nice going everyone! #teamworkmakesthedreamwork

I'll mint a DOI for this record today. To do so, I'll have to briefly publish the record in the Hakai Catalogue to get the xml file (so you might briefly see it in the catalogue without a DOI). @carolynisabella @hakaiholmes @zmonteith some minor changes I'm proposing/question I have:
1. I noticed the 'date published' is 2023-04-30; just want to confirm -- should this be 2023-04-03?
2. I'll add 'Hakai Institute' as associated affiliation for all authors;
3. When giving Hakai Institute the role of publisher, make sure you check the box to have it appear in the citation as well :)

**Comment by carolynisabella** [comment]
Thanks for all of your help, everyone! To answer your questions, Tim:

   1. I noticed the 'date published' is 2023-04-30; just want to confirm --
   should this be 2023-04-03?
   *I guess I was thinking about the date published of the manuscript,
   which I don't know for sure but assuming within the next month. We can just
   that to 03 or whatever makes sense if it's more related to the metadata
   record itself*

   2. I'll add 'Hakai Institute' as associated affiliation for all authors;

   *Thanks for doing that!*

   3. When giving Hakai Institute the role of publisher, make sure you
   check the box to have it appear in the citation as well :)

   *Sounds good -- I think I did that initially, but then it seemed
   redundant to have Hakai Institute as an author, and also at the end of the
   citation - but however you usually do it is fine! *


Thanks again, Tim! If you can send along the DOI when you have it, that'd
be great!

**Comment by zmonteith** [comment]
@timvdstap I unchecked Hakai from the citation. It doesn't make sense to me to include the organization in the citation information. I haven't seen other institutions included in citations before (ie. SFU, MBARI, MarineGEO, etc.), unless it's a newer development I've missed. As well, this information is implicitly included via the authors affiliations.

Just my thoughts.

**Comment by timvdstap** [comment]
@zmonteith I agree with you and I think I just hadn't made myself clear enough -- I would only recommend adding Hakai Institute as 'Publisher', not as an author to the recommended citation. This would change it as follows:

currently: Prentice, C., Olson, A. M., Meagher Robinson, K., Clemente-Carvalho, R., Hall, K., Monteith, Z. L., Morien, E., Pontier, O., Hessing-Lewis, M., Kellogg, C., & Lemay, M. (2023). Biodiversity Surveys of the Gwaxdlala/Nalaxdlala Indigenous Protected and Conserved Area (IPCA) in Knight Inlet, British Columbia (v1.0).

proposed: Prentice, C., Olson, A. M., Meagher Robinson, K., Clemente-Carvalho, R., Hall, K., Monteith, Z. L., Morien, E., Pontier, O., Hessing-Lewis, M., Kellogg, C., & Lemay, M. (2023). Biodiversity Surveys of the Gwaxdlala/Nalaxdlala Indigenous Protected and Conserved Area (IPCA) in Knight Inlet, British Columbia (v1.0). Hakai Institute

**Comment by zmonteith** [comment]
@timvdstap thanks for clarifying, that makes a lot more sense. I see now how the publisher field is analogous to if this was published in a journal.

**Comment by carolynisabella** [comment]
Ah, I see - that looks good to me! Sorry I may have changed that by
accident, I thought it was already set up as the second version. :)

**Comment by timvdstap** [comment]
DOI minted and finalized: https://doi.org/10.21966/wabn-bq33
