### ISSUE TITLE
Dataset - nate test (Copy)

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#56]
## nate test (Copy)

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/hM2aN3v9MzZ6J4KGMOEW2s9gidj2/-NFG7yhJmjwvMimZYpGP

### In General

- [ ] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [ ] No version information in the title
- [ ] Frontloaded (with the most important information first)
- [ ] Include the geographical region the data apply to
- [ ] Short – aim for 60 characters including spaces
- [ ] Does not include acronyms – put these in the keywords
- [ ] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title
- [ ] Does not include the time period (this is covered in the temporal extents fields)

#### Abstract

- [ ] Abbreviations have been expanded upon at first mention

### Spatial

- [ ] Ensure that Depth or Height Positive is correctly selected

### Contact

- [ ] ROR and ORCID(s) are included and linked properly where applicable
- [ ] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [ ] The citation in the metadata record matches the preferred citation mentioned in the data package.
- [ ] Include Hakai Institute as Publisher (& Distributor?)
- [ ] Make sure email address is provided if the role is 'Point of Contact'
- [ ] Add contact affiliation where known

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package
- [ ] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [ ] Links work
- [ ] Resource link links to a download of the compressed data package (.zip) of the correct version.
- [ ] All files in the data package can be opened and are not corrupt

**Comment by pramod-thupaki** [comment]
Looks good. I would add:
- make title unique (or avoid duplicating existing titles)
- limit abstract to ~ 250 words; extra material can be included in data package as supplementary information
- no executable files in data package; stick to open formats and standards; retain same standards across versions where possible;
- preference to institutional emails where possible under contact information;

**Comment by n-a-t-e** [comment]
See https://github.com/cioos-siooc/metadata-entry-form/blob/main/firebase-functions/functions/dataset-name.md for the template that this issue was created from

**Comment by Br-Johnson** [comment]
Update metadata review checklist as per Pramods suggestions, plus added a few of my own. https://github.com/cioos-siooc/metadata-entry-form/commit/42504ae9bf352d02b5a7fe6d3833bb6a1ec813fd
