### ISSUE TITLE
Dataset - Seagrass Site-Level Production on BC Central Coast

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#58]
## Seagrass Site-Level Production on BC Central Coast

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/lJHlH9nm20QQOPuk217xLlxWbNv1/-NPt7-mgrZEUzma8l5W_

### In General

- [ ] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [ ] No version information in the title
- [ ] Frontloaded (with the most important information first)
- [ ] Include the geographical region the data apply to
- [ ] Short – aim for 60 characters including spaces
- [ ] Does not include acronyms – put these in the keywords
- [ ] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title
- [ ] Does not include the time period (this is covered in the temporal extents fields)

#### Abstract

- [ ] Abbreviations have been expanded upon at first mention

### Spatial

- [ ] Ensure that Depth or Height Positive is correctly selected

### Contact

- [ ] ROR and ORCID(s) are included and linked properly where applicable
- [ ] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [ ] The citation in the metadata record matches the preferred citation mentioned in the data package.
- [ ] Include Hakai Institute as Publisher (& Distributor?)
- [ ] Make sure email address is provided if the role is 'Point of Contact'
- [ ] Add contact affiliation where known

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package
- [ ] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [ ] Links work
- [ ] Resource link links to a download of the compressed data package (.zip) of the correct version.
- [ ] All files in the data package can be opened and are not corrupt

**Comment by timvdstap** [comment]
Hey @zmonteith ! Hope you had a wonderful Christmas! If I'm not mistaken, this record has been published: https://doi.org/10.21966/ezev-0v96 right? 

I just changed one minor thing: I've included the OBIS record as a 'Related Work', rather than the Primary Resource, mainly because the OBIS record covers 2015 - 2019 whereas the full dataset contains data till 2022. Please let me know if you disagree and we can reopen this issue.

**Comment by zmonteith** [comment]
Thanks for following up Tim.

Yes, should be the same record with updated data.

Sounds go re: changes to OBIS record relationship.

Happy New Year,

---
Zach Monteith
Hakai Institute <http://hakai.org>
***@***.***
250-285-2628
