### ISSUE TITLE
Dataset - Conductivity, Temperature and Depth (CTD) Water Column Profile Data from the Hakai Institute Juvenile Salmon Program

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#59]
## Conductivity, Temperature and Depth (CTD) Water Column Profile Data from the Hakai Institute Juvenile Salmon Program

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/UTb9hNU3GJRK302QyaKNIvj2OiJ2/-NcYL5JndZWMdXmXuFqB

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [x] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [x] Time series datasets should include “time series” at the end of the title
- [x] Does not include the time period (this is covered in the temporal extents fields)

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [x] Abstract describes how, when, what, where, why of data collection and is limited to ~ 250 words

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [x] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher, Distributor, and Owner (if applicable) and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] Use institutional email adresses where possible for contacts

### Resources

- [x] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [x] Readme, changelog, data dictionary, protocols included in data-package
- [x] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [x] All files in the data package can be opened and are not corrupt
- [x] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by JessyBarrette** [comment]
I guess one think maybe to be consistent with the rest of the hakai ctd datasets is to add the Provisional within the title since this is pulling data from the provisional ctd dataset.

**Comment by JessyBarrette** [comment]
We've also used in the ctd datasets too the term water properties instead of just CTD since other sensors data is available. 

I would suggest renaming the title:
> Vertical Water Properties Profiles from the Hakai Institute Juvenile Salmon Program, Provisional

**Comment by JessyBarrette** [comment]
I would add Hakai Institute as a publisher too

**Comment by Br-Johnson** [comment]
OK I addressed all those points. I also added a Resource link the Processing/QA/QC manual: https://github.com/HakaiInstitute/hakai-datasets/raw/development/datasets_documents/HakaiWaterPropertiesProfiles/Hakai_Water_Properties_Processing_and_QAQC_Procedure_20210331.pdf

I added '(CTD)' to the title since thats the common vernacular for this data type.

**Comment by JessyBarrette** [comment]
It all looks good to me @Br-Johnson Feel free to close that issue.

**Comment by Br-Johnson** [comment]
Thanks Jessy!
