### ISSUE TITLE
Dataset - Kelp and Seagrass Mapping – 2022 – Hakai Airborne Coastal Observatory

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#60]
## Kelp and Seagrass Mapping – 2022 – Hakai Airborne Coastal Observatory

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/RvRPlFMSsIaBwoGdQIq5BVYfBBa2/-NM17eClIayI651ZLazJ

### In General

- [ ] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [ ] No version information in the title
- [ ] Frontloaded (with the most important information first)
- [ ] Include the geographical region the data apply to
- [ ] Short – aim for 60 characters including spaces
- [ ] Does not include acronyms – put these in the keywords
- [ ] Does not include the word “dataset”
- [ ] Time series datasets should include “time series” at the end of the title
- [ ] Does not include the time period (this is covered in the temporal extents fields)

#### Abstract

- [ ] Abbreviations have been expanded upon at first mention
- [ ] Abstract describes how, when, what, where, why of data collection and is limited to ~ 250 words

#### DOI

 - [ ] A DOI has been drafted for this record
 - [ ] DOI has been updated via the form after review and changes to record
 - [ ] DOI has been manually edited on datacite fabrica
 - [ ] DOI status has been changed from Draft to Findable

### Spatial

- [ ] Ensure that Depth or Height Positive is correctly selected

### Contact

- [ ] ROR and ORCID(s) are included and linked properly where applicable
- [ ] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [ ] Include Hakai Institute as Publisher, Distributor, and Owner (if applicable) and include data@hakai.org as email
- [ ] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [ ] Add contact affiliation where known including ROR
- [ ] Use institutional email adresses where possible for contacts

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package
- [ ] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [ ] Links work
- [ ] All files in the data package can be opened and are not corrupt
- [ ] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by timvdstap** [comment]
@hakaiholmes I'm sorry, this completely flew under my radar! I'll make sure to look at it tomorrow!

**Comment by timvdstap** [comment]
DOI minted, closing this ticket: https://doi.org/10.21966/8WBR-VK04
