### ISSUE TITLE
Dataset - Spatial extent of eelgrass (Zostera marina) meadows from monitoring sites within Gwaii Haanas National Park Reserve, National Marine Conservation Area Reserve, and Haida Heritage Site (2016, 2017, 2018) mapped using remote piloted aerial systems (RPAS) v1.0.0

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#62]
## Spatial extent of eelgrass (Zostera marina) meadows from monitoring sites within Gwaii Haanas National Park Reserve, National Marine Conservation Area Reserve, and Haida Heritage Site (2016, 2017, 2018) mapped using remote piloted aerial systems (RPAS) v1.0.0

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/owhqxLMKaJdQBPGxgc2FH82HfLp1/-NeEpZEr5wOQ_rWGa5CN

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [x] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [x] Time series datasets should include “time series” at the end of the title

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [ ] Abstract describes how, when, what, where, why of data collection and is limited to ~ 250 words

#### DOI

- [x] A DOI has been drafted for this record
- [x] DOI has been updated via the form after review and changes to record
- [x] DOI has been manually edited on datacite fabrica
- [x] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [x] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher, Distributor, and Owner (if applicable) and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] Use institutional email adresses where possible for contacts

### Resources

- [x] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [x] Readme, changelog, data dictionary, protocols included in data-package
- [x] Links work
- [ ] All files in the data package can be opened and are not corrupt
- [x] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by hakaiholmes** [comment]
I made a few changes here - feel free to ping me or Luba if needed.

**Comment by Br-Johnson** [comment]
Hey @hakaiholmes and @lreshitnyk  I just had a look through the metadata record and noticed a number of the review checklist items (above) need some attention. All just minor stuff but best practices. As a side note I'm going to update the metadata intake form so that these review criteria are all included in there. Some of them are currently not, so not your fault.

**Comment by hakaiholmes** [comment]
Thank you - yes, I see the missing items listed. I will review it with Luba.
