### ISSUE TITLE
Dataset - Daily satellite (Sentinel 3A and 3B) chlorophyll and suspended matter concentrations for coastal British Columbia and southeast Alaska

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#69]
## Daily satellite (Sentinel 3A and 3B) chlorophyll and suspended matter concentrations for coastal British Columbia and southeast Alaska

<https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/7U7b8oPpeTN6gjvXlUCTGJr5pga2/-NTteirxDjvnABVz_7Dh>

### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [x] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [x] Time series datasets should include “time series” at the end of the title

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [x] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [x] A DOI has been drafted for this record
- [x] DOI has been updated via the form after review and changes to record
- [x] DOI has been manually edited on datacite fabrica
- [x] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [x] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] Use institutional email adresses where possible for contacts

### Resources

- [x] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [x] Readme, changelog, data dictionary, protocols included in data-package
- [x] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [x] All files in the data package can be opened and are not corrupt
- [x] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by JessyBarrette** [comment]
@jdelbel I'm looking at this right now. 

- [ ] Do you know if the Spectral Lab as a ROR id?
- [ ] Should we generate a DOI for those two datasets separately?
- [x] The abstract is a bit long but that's ok we live with it.
- [ ] Should we move up the <www.algaeexplorer.ca> page as the primary resource?

The same questions applies to #68

**Comment by jdelbel** [comment]
I haven't been able to find a spectral lab ROR id, so I suspect no. Is it worth requesting Maycira to make one?

I'm not sure on the DOI front. They are different datasets, so I suspect yes. 

Did you see that I combined Chlorophyll and TSM for daily and 8-day? Just want to confirm.

Good catch. I didn't realize order matters. I have reorganized on both datasets.

**Comment by JessyBarrette** [comment]
ok for ROR you can perhaps ask Macira it can always be added after. It would handy for her in the future to link any DOI relate to her research group.

Two separated DOI, I'm ok with that. Chloropyll and TSM together in each I think is fine.

**Comment by JessyBarrette** [comment]
what is the platform id 65?

**Comment by jdelbel** [comment]
Weird, I'm confident I found that on the ICES Platform code webpage, but can't find it now, so I'm either hallucinating or they removed it. I couldn't find any reference to the Sentinel Satellite platform, so will delete off both records now.

**Comment by jdelbel** [comment]
Actually, it was from NVS... https://vocab.nerc.ac.uk/collection/L06/current/65/

Worth keeping or remove as not applicable there as not on ICES?

**Comment by JessyBarrette** [comment]
ok that is related to the platform and not ICES that's ok. I guess 65 `orbiting satellite` is more specific and match this dataset I'll update the platform to it then

**Comment by Br-Johnson** [comment]
For RORs we generally use the parent organization and then and child organizations if they have a ROR. So in this case it probably just makes sense to use the UVic ROR

**Comment by JessyBarrette** [comment]
Oops I replaced the ROR by the UVic one but it also dropped the Spectral Lab reference not sure what it should be

**Comment by jdelbel** [comment]
OK, it doesn't look like you alter the ROR to add the spectral lab in, but we can alter the address and currently it has the department of geography listed. We could potentially put Spectral Lab in there? What would be better, Spectral lab without ROR link or ROR link and less emphasis on spectral lab?

**Comment by Br-Johnson** [comment]
I would just add Spectral Lab to the address

**Comment by jdelbel** [comment]
Ok, record is updated with the spectral lab in the address field.

**Comment by JessyBarrette** [comment]
@jdelbel We're good to go now with this dataset you can generate a DOI by clicking on Generate DOI then we can publish this dataset :) 


The erddap dataset is now available on catalogue.hakai.org/erddap

**Comment by jdelbel** [comment]
@JessyBarrette Ok, Draft DOI generated and record saved for both datasets. Let me know if it worked.

**Comment by JessyBarrette** [comment]
This record is now live and active
