### ISSUE TITLE
Invalid DOI?

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/metadata-review#72]
I'm not sure if this is related to lates the changes not been include on the form yet. But here's one metadata record that can't be submitted for review due to an invalid DOI

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/7U7b8oPpeTN6gjvXlUCTGJr5pga2/-McQFPAf457LB4-SWmyL

@Br-Johnson @timvdstap @sorochak any thoughts?

**Comment by timvdstap** [comment]
Was that DOI generated through the form? If it was manually put in, try adding https://doi.org/ in front of it.

See e.g. https://github.com/cioos-siooc/metadata-entry-form/issues/230

**Comment by JessyBarrette** [comment]
This still prevents us from publish this dataset. I have no control on the DOI myself. And I believe that DOI is still in Draft

This leads to nothing: https://doi.org/10.21966/fg51-ms50

**Comment by JessyBarrette** [comment]
yeah that old Draft was never used, I can delete and regenerate a new one, which I just did. DOI is now `10.21966/90h6-b497`

Now, the Draft DOI was generated by the form. However, I can't still submit the form due to an `Invalid DOI` 😞

**Comment by timvdstap** [comment]
@n-a-t-e do you perhaps have any thoughts on this?

**Comment by sorochak** [comment]
The invalid DOI message occurs because our DOI validation checks to make sure it is a valid Http URL. 

The simplest solution is to remove the http check and remove `http://doi/` from any current records that have it. The datacite api doesn't handle urls either, so we would have to add/remove the url portion on create/update.

What was the reasoning behind adding the http url portion to the DOIs ?

**Comment by n-a-t-e** [comment]
it can be stored with or without that `http://doi/` . Either way, all the records in the DB need to be updated to be either with or without `http://doi/` for consistency

One reason to store it *with http* in the database, is there are at least 3 places I can see where this url gets used, in its full url form:
 - EML
 - ISO XML
 - erddap XML snippet

So if we don't store with `http://doi/` in the DB, we just have to tack it on in those 3 spots

Also, how we store in the DB vs what we ask on the form dont need to be related, we can store full URL and just ask for 10.000/1234 in the form, and then split/reform as needed

**Comment by fostermh** [comment]
I am in favour of storing it as the full url. it is easy to strip off the https://doi.org/ part when making calls to datacite and it avoids ambiguity in down stream applications that use the identifier.

**Comment by sorochak** [comment]
All DOIs in the DB are now be stored as the full url.

**Comment by JessyBarrette** [comment]
Awesome thanks everyone the record associated with this issue also succeeded to be submitted. I think I can now close this issue.
