### ISSUE TITLE
Nuchatlaht Survey - Hakai Airborne Coastal Observatory - Nootka Island British Columbia - 2023

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/metadata-review#73]
### In General

- [x] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [x] No version information in the title
- [x] Frontloaded (with the most important information first)
- [x] Include the geographical region the data apply to
- [x] Short – aim for 60 characters including spaces
- [x] Does not include acronyms – put these in the keywords
- [x] Does not include the word “dataset”
- [x] Time series datasets should include “time series” at the end of the title

#### Abstract

- [x] Abbreviations have been expanded upon at first mention
- [x] Abstract describes how, when, what, where, why of data collection and is limited to no more than 500 words

#### DOI

- [x] A DOI has been drafted for this record
- [ ] DOI has been updated via the form after review and changes to record
- [ ] DOI has been manually edited on datacite fabrica
- [ ] DOI status has been changed from Draft to Findable

### Spatial

- [x] Ensure that Depth or Height Positive is correctly selected

### Contact

- [x] ROR and ORCID(s) are included and linked properly where applicable
- [x] For datasets where DFO is a partner, ensure 'parent' ROR is added (https://ror.org/02qa1x782). DFO 'child' organizations (i.e. CHS) and their ROR are optional.
- [x] Include Hakai Institute as Publisher and include data@hakai.org as email
- [x] Make sure email address is provided if the role is 'Metadata Custodian' or 'Point of Contact' 
- [x] Add contact affiliation where known including ROR
- [x] Use institutional email adresses where possible for contacts

### Resources

- [x] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package
- [x] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [x] Links work
- [x] All files in the data package can be opened and are not corrupt
- [x] No executable files in the data package. Files should be open formats and standards (.csv, .txt for example)

**Comment by Br-Johnson** [comment]
@hakaiholmes Just a few notes:
1. Not clear what the dataset contains based on the title for external users. I think it's LiDaR topography data but others may now know right away. 
2. Probably should expand on LiDAR acronym. I already expanded ACO.

Looks good otherwise!

@timvdstap It's kind of interesting this metadata record isn't really for the data, it's for the metadata report. This is another reason why we need to have more options for labelling a records "Resource Type" beyond dataset to include reports etc...

**Comment by hakaiholmes** [comment]
Thank you for the review. I will get right on the edits. 
The catalog link will be shared along with an FTP link to the Nation, BC Parks, and Archaeologist that has all the ACO data. Due to the size of the files and the sensitive nature of the data, we can't have direct public access to the data. A different classification may help make that clear to users. Thanks again team!
