### ISSUE TITLE
Dataset - 100 Islands Research Program Terrestrial Vegetation Data - BC Central Coast - 2015, 2016, 2017

### ISSUE THREAD

**Issue by hakai-it** [HakaiInstitute/metadata-review#9]
## 100 Islands Research Program Terrestrial Vegetation Data - BC Central Coast - 2015, 2016, 2017

https://cioos-siooc.github.io/metadata-entry-form/#/en/hakai/qbqh6DF00XZq8MOpQ3kKkI9GUv43/-MWN3eXE0MWhrdGJzTXg

### In General
- [ ] No previous versions of this metadata record exist (eg for earlier versions of the data, if so update that record rather than creating a new one)

#### Dataset title:

- [ ] No version information in the title
- [ ] Frontloaded (with the most important information first) 
- [ ] Include the geographical region the data apply to 
- [ ] Short – aim for 60 characters including spaces 
- [ ] Does not include acronyms – put these in the keywords 
- [ ] Does not include the word “dataset” 
- [ ] Time series datasets should include “time series” at the end of the title 
- [ ] Does not include the time period (this is covered in the temporal extents fields)

#### Abstract

- [ ] Abbreviations have been expanded upon at first mention

### Spatial

- [ ] Ensure that Depth or Height Positive is correctly selected

### Contact

- [ ] No organizations listed under first / last name
- [ ] ROR and ORCID(s) are included and linked properly where applicable
- [ ] The citation in the metadata record matches the preferred citation mentioned in the data package. 
- [ ] Include Hakai Institute as Publisher (& Distributor?)

### Resources

- [ ] Resource links go to specific dataset download (not generic platform like waterproperties.ca)
- [ ] Readme, changelog, data dictionary, protocols included in data-package
- [ ] An archive folder for older data versions is included in the data package if the version is _not_ 1.0
- [ ] Links work
- [ ] Resource link links to a download of the compressed data package (.zip) of the correct version.
- [ ] All files in the data package can be opened and are not corrupt

**Comment by timvdstap** [comment]
@timvdstap need to keep track of this record, as currently the recommended citation does not include authors in CKAN.

**Comment by hakaiholmes** [comment]
I resolved a few issues here. I think it is good to go, but maybe worth getting it triple-checked by someone else on the data mobe team just to be safe? 
@timvdstap

**Comment by Br-Johnson** [comment]
@timvdstap Just wondering if this can be closed?
